export const content = {
    EN: {
        title: "BNB Price Statistics",
        BinanceCoinPriceToday: "Binance Coin Price Today",
        BinanceCoinPrice: "Binance Coin Price ",
        PriceChange: "Price Change",
        LowHigh24h: "24h Low / 24h High",
        TradingVolume: "Trading Volume",
        VolumeMarketCap: "Volume / Market Cap",
        MarketDominance: "Market Dominance",
        MarketRank: "Market Rank",
        BinanceCoinPriceCap: "Binance Coin Price Cap",
        MarketCap: "Market Cap",
        FullyDilutedMarketCap: "Fully Diluted Market Cap",
        BinanceCoinPriceToday: "Binance Coin Price Today",
        YesterdaysLowHigh: "Yesterday’s Low / High",
        YesterdaysOpenClose: "Yesterday’s Open / Close",
        YesterdaysChange: "Yesterday’s Change",
        YesterdaysVolume: "Yesterday’s Volume",
        BinanceCoinPriceToday: "Binance Coin Price Today",
        LowHigh7d: "7d Low / 7d High",
        LowHigh30d: "30d Low / 30d High",
        LowHigh90d: "90d Low / 90d High",
        LowHigh52week: "52 Week Low / 52 Week High",
        AllTimeHigh: "All Time High",
        MayMonthAgo: "May 10, 2021 (5 month ago)",
        BinanceCoinRoi: "Binance Coin Roi",
        BinanceCoinSupply: "Binance Coin Supply",
        CirculationSupply: "Circulation Supply",
        TotalSupply: "Total Supply",
        MaxSupply: "Max Supply",
        ShowMore: "Show more",
        ShowLess: "Show less",

    },
    RU: {
        title: "BNB Price Statistics",
        BinanceCoinPriceToday: "Цена монеты Binance сегодня",
        BinanceCoinPrice: "Цена монеты Binance",
        PriceChange: "Изменение цены",
        LowHigh24h: "24ч Низкий / 24ч Высокий",
        TradingVolume: "Объем торгов",
        VolumeMarketCap: "Объем / рыночная капитализация",
        MarketDominance: "Доминирование на рынке",
        MarketRank: "Рыночный рейтинг",
        BinanceCoinPriceCap: "Ограничение цены Binance Coin",
        MarketCap: "Рыночная капитализация",
        FullyDilutedMarketCap: "Полностью разводненная рыночная капитализация",
        BinanceCoinPriceToday: "Цена монеты Binance сегодня",
        YesterdaysLowHigh: "Вчерашний минимум / максимум",
        YesterdaysOpenClose: "Вчерашнее открытие / закрытие",
        YesterdaysChange: "Вчерашнее изменение",
        YesterdaysVolume: "Вчерашний объем",
        BinanceCoinPriceToday: "Цена монеты Binance сегодня",
        LowHigh7d: "7д Низкий / 7д Высокий",
        LowHigh30d: "30д низкий / 30д высокий",
        LowHigh90d: "90д Низкий / 90д Высокий",
        LowHigh52week: "52-недельный минимум / 52-недельный максимум",
        AllTimeHigh: "Самые высокие за все время сущ.",
        MayMonthAgo: "10 мая 2021 г. (5 месяцев назад)",
        BinanceCoinRoi: "Binance Coin Roi",
        BinanceCoinSupply: "Поставка монет Binance",
        CirculationSupply: "Циркуляционное снабжение",
        TotalSupply: "Общее предложение",
        MaxSupply: "Максимальное предложение",
        ShowMore: "Показать больше",
        ShowLess: "Показывай меньше",

    }
}