export const Style = {
    background: {
        position: "absolute", 
        left: 0, 
        top: 0,
        width: "100%",
        height: "100%",
        justifyContent: "center",
        alignItems: 'center',
        backgroundColor: "rgba(0, 0, 0, 0.6)",
    },
    blockDark: {
        width: "80%",
        height: "auto",
        backgroundColor: "#1C1C1E",
        padding: 14,
        borderRadius: 15,
        borderWidth: 1,
        borderColor: "#424246",
    },
    blockLight: {
        width: "80%",
        height: "auto",
        backgroundColor: "#fff",
        padding: 14,
        borderRadius: 15,
        borderWidth: 1,
        borderColor: "#D6D6D6",
    },
    confirm: {
        widht: "100%",
        padding: 16,
        backgroundColor: "#2E9C3E",
        borderRadius: 10, 
    },
    confirmText: {
        color: "#fff",
        fontSize: 15,
        textAlign: "center",
    },
    cancel: {
        widht: "100%",
        padding: 16,
        borderWidth: 1,
        borderColor: "#2E9C3E",
        borderRadius: 10, 
    },
    cancelText: {
        color: "#2E9C3E",
        fontSize: 15,
        textAlign: "center",
    },
    balance: {
        widht: "100%",
        padding: 16,
        backgroundColor: "#424246",
        borderRadius: 10, 
    },
    balanceText: {
        color: "rgba(255, 255, 255, 0.5)",
        fontSize: 15,
        textAlign: "center",
    },
}