export const content = {
    EN: {
        Setting: "Setting",
        Language: "Language",
        English: "English",
        EnglishSelect: "English",
        RussianSelect: "Russian",
        InfoAndSettings: "Info and settings",
        name: "Name",
        username: "Username",
        Security: "Security",
        Email: "E-mail",
        PhoneNumber: "Phone number",
        Password: "Password",
        TwoFactorAuthentication: "Two factor authentication",
        SecurityScreen: "Security screen",
        SeedPhrase: "Seed phrase",
        Show: "Show",
        Privacy: "Privacy",
        HideSubscribers: "Hide subscribers",
        HideSubscriptions: "Hide subscriptions",
        HideWallet: "Hide wallet",
        HideWalletAdress: "Hide wallet adress",
        HideStatistics: "Hide statistics",
        Logout: "Logout",

    },
    RU: {
        Setting: "Настройки",
        English: "Русский",
        Language: "Язык",
        EnglishSelect: "Английский",
        RussianSelect: "Русский",
        InfoAndSettings: "Информация и настройки",
        name: "Имя",
        username: "Username",
        Security: "Безопасность",
        Email: "Эл. почта",
        PhoneNumber: "Номер телефона",
        Password: "Пароль",
        TwoFactorAuthentication: "Двухфакторная аутентификация",
        SecurityScreen: "Экран безопасности",
        SeedPhrase: "Исходная фраза",
        Show: "Показывать",
        Privacy: "Конфиденциальность",
        HideSubscribers: "Скрыть подписчиков",
        HideSubscriptions: "Скрыть подписки",
        HideWallet: "Скрыть кошелек",
        HideWalletAdress: "Скрыть адрес кошелька",
        HideStatistics: "Скрыть статистику",
        Logout: "Выйти",

    }
}